version: '3.8'

services:
  # Database
  mongo:
    image: mongo:latest
    container_name: mean-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend API
  backend:
    build: ./backend
    container_name: mean-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mean-db
      # Yahan humne bata diya ki DB ka naam 'mongo' hai, localhost nahi.

  # Frontend UI
  frontend:
    build: ./frontend
    container_name: mean-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: